### ISSUE TITLE
根据文件路径获取不到文件

### ISSUE THREAD

**Issue by ITBeyond1024** [xuexiangjys/XHttp2#40]
因为项目需要用SDK30，上传文件时，出现：
I/[XHttp]: <-- HTTP FAILED: /storage/emulated/0/Android/data/com.xuexiang.templateproject/cache/XQRCode_1652508557266.png (No such file or directory)
E/[XHttp]: --> Subscriber is onError
E/[XHttp]: --> e instanceof ApiException, message:java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.xuexiang.templateproject/cache/XQRCode_1652508557266.png (No such file or directory)
E/[XHttp]: com.xuexiang.xhttp2.exception.ApiException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.xuexiang.templateproject/cache/XQRCode_1652508557266.png (No such file or directory)
        at com.xuexiang.xhttp2.exception.ApiExceptionHandler.handleException(ApiExceptionHandler.java:51)
        at com.xuexiang.xhttp2.transform.func.HttpResponseThrowableFunc.apply(HttpResponseThrowableFunc.java:34)
        at com.xuexiang.xhttp2.transform.func.HttpResponseThrowableFunc.apply(HttpResponseThrowableFunc.java:31)
        at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:91)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:77)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:60)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.xuexiang.templateproject/cache/XQRCode_1652508557266.png (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at okio.Okio.source(Okio.kt:194)
        at okhttp3.RequestBody$3.writeTo(RequestBody.java:119)
        at com.xuexiang.xhttp2.request.body.UploadProgressRequestBody.writeTo(UploadProgressRequestBody.java:87)
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
        at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.xuexiang.xhttp2.interceptor.NoCacheInterceptor.intercept(NoCacheInterceptor.java:36)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorC
E/[XHttp]: hain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.xuexiang.xhttp2.interceptor.HeadersInterceptor.intercept(HeadersInterceptor.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.xuexiang.xhttp2.interceptor.NoCacheInterceptor.intercept(NoCacheInterceptor.java:36)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.xuexiang.xhttp2.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:110)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
        	... 18 more

**Comment by xuexiangjys** [comment]
你文件都没有，何来的获取文件？

**Comment by ITBeyond1024** [comment]
抱歉，用例一个计算时间戳函数命名文件，导致文件找不到，感谢您的回复！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 凌晨0:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuexiangjys/XHttp2] 根据文件路径获取不到文件 (Issue #40)






你文件都没有，何来的获取文件？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;
