### ISSUE TITLE
Subscriber is onError

### ISSUE THREAD

**Issue by molele2** [xuexiangjys/XHttp2#6]
ttp]: -------------------------------response-------------------------------
I/[XHttp]: <-- 200  http://192.168.1.101:19081/shoes/query/89851 (271ms）
     
I/[XHttp]: 	Content-Type: application/json;charset=UTF-8
I/[XHttp]: 	Transfer-Encoding: chunked
    	Date: Mon, 04 Feb 2019 05:04:16 GMT
I/[XHttp]: 	Cache-Control: no-cache
I/[XHttp]:  
I/[XHttp]: 	body:{"shoes":{"id":8,"name":"Belle/百丽冬季专柜同款黑色牛皮/人造革男休闲鞋5KF01DM7","price":"439","buyer":2122,"type":1,"cover":"http://res.warunion.com/shoes/89851/100573221.jpg","identifier":89851,"size":"40，41，42，43，44","color":"黑色，白色，蓝色","shopid":0,"isself":0,"status":0,"slaveprice":111.0,"quantity":345,"currenttime":"2019-02-03"},"images":[{"id":1,"identifier":222,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_00_b.jpg","imagestatus":1,"shoesorder":1},{"id":2,"identifier":221,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_01_b.jpg","imagestatus":1,"shoesorder":2},{"id":3,"identifier":223,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_02_b.jpg\r\n","imagestatus":1,"shoesorder":3},{"id":4,"identifier":224,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_03_b.jpg\r\n","imagestatus":1,"shoesorder":4},{"id":5,"identifier":225,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_04_b.jpg\r\n","imagestatus":1,"shoesorder":5},{"id":6,"identifier":226,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_10_b.jpg\r\n","imagestatus":1,"shoesorder":6},{"id":7,"identifier":227,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_11_b.jpg\r\n","imagestatus":1,"shoesorder":7},{"id":8,"identifier":228,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_12_b.jpg","imagestatus":1,"shoesorder":8},{"id":9,"identifier":229,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_40_b.jpg","imagestatus":1,"shoesorder":9},{"id":10,"identifier":230,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_41_b.jpg\r\n","imagestatus":1,"shoesorder":10},{"id":11,"identifier":231,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_42_b.jpg\r\n","imagestatus":1,"shoesorder":11},{"id":12,"identifier":232,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_51_b.jpg\r\n","imagestatus":1,"shoesorder":12},{"id":13,"identifier":233,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_52_b.jpg\r\n","imagestatus":1,"shoesorder":13},{"id":14,"identifier":234,"shoesidentifier":89851,"imageaddr":"http://res.warunion.com/shoes/89851/100573221_52_b.jpg\r\n","imagestatus":1,"shoesorder":14}]}
I/[XHttp]: <-- END HTTP
E/[XHttp]: --> Subscriber is onError
    --> e instanceof ApiException, message:空指针错误
E/[Logger]: com.xuexiang.xhttp2.exception.ApiException: 空指针错误
        at com.xuexiang.xhttp2.exception.ApiExceptionHandler.handleException(ApiExceptionHandler.java:51)
        at com.xuexiang.xhttp2.transform.func.HttpResponseThrowableFunc.apply(HttpResponseThrowableFunc.java:34)
        at com.xuexiang.xhttp2.transform.func.HttpResponseThrowableFunc.apply(HttpResponseThrowableFunc.java:31)
        at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:91)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/EGL_emulation: eglMakeCurrent: 0xdd305480: ver 2 0 (tinfo 0xdd303790)
D/EGL_emulation: eglMakeCurrent: 0xdd305480: ver 2 0 (tinfo 0xdd303790)

**Comment by xuexiangjys** [comment]
json的格式不符合规范。

需要注意的是，所以请求返回的结果必须要满足以下格式:

```
{
    "Code":0, //响应码，0为成功，否则失败
    "Msg":"", //请求失败的原因说明
    "Data":{} //返回的数据对象
}
```

**Comment by xuexiangjys** [comment]
像你这种毫无规范的数据返回体，不适合使用本框架。推荐使用[okgo](https://github.com/jeasonlzy/okhttp-OkGo)
