### ISSUE TITLE
使用自定义请求响应，获取不到result

### ISSUE THREAD

**Issue by Weiyi-C** [xuexiangjys/XHttp2#9]
## 问题描述
由于请求返回code为字符串且正常码为“00000000”，所以自定义了请求响应  
只对errorCode做了Integer.parseInt(errorCode)，但在运行时报空指针错误，打断点发现除了errorCode为0，errorInfo和result均为null

## 使用的XHttp2版本
1.0.2

## 如何重现
自定义请求响应，将参考的
```java
    public CustomApiResult<T> setErrorCode(int errorCode) {
        this.errorCode = errorCode;
        return this;
    }
```
修改为
```java
    public CustomApiResult<T> setErrorCode(String errorCode) {
        this.errorCode = Integer.parseInt(errorCode);
        return this;
    }
```
请求方式
```java
XHttp.post("/test/res")
                .baseUrl(App.URL_BASE)
                .execute(new CallBackProxy<CustomApiResult<Response>, Response>(new SimpleCallBack<Response>() {
                    @Override
                    public void onSuccess(Response response) throws Throwable {
                        callBack.onSuccess(response);
                    }

                    @Override
                    public void onError(ApiException e) {
                        callBack.onError(e);
                    }
                }){});
```

## 期望的效果
正常获得返回值

## 截图
![断点截图](https://user-images.githubusercontent.com/34223095/70028481-be21d500-15df-11ea-8090-4b6709ced844.png)

日志
```
2019-12-03 15:30:03.005 21871-25669/com.SpaceElves.box I/XHttp: -------------------------------response-------------------------------
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp: <-- 200 OK https://prod.api.spaceevels.com/test/res (346ms）
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp:  
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp: 	Server: nginx
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp: 	Date: Tue, 03 Dec 2019 07:30:03 GMT
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp: 	Content-Type: application/json; charset=UTF-8
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp: 	Transfer-Encoding: chunked
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp: 	Connection: keep-alive
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp: 	X-Powered-By: PHP/7.3.0
2019-12-03 15:30:03.006 21871-25669/com.SpaceElves.box I/XHttp: 	Cache-Control: no-cache
2019-12-03 15:30:03.007 21871-25669/com.SpaceElves.box I/XHttp:  
2019-12-03 15:30:03.008 21871-25669/com.SpaceElves.box I/XHttp: 	body:{"code":"00000000","msg":"服务调用成功！","data":{"token":"eaa824d3b50a53d38200084373e5f626"}}
2019-12-03 15:30:03.008 21871-25669/com.SpaceElves.box I/XHttp: <-- END HTTP
2019-12-03 15:30:03.016 21871-25669/com.SpaceElves.box D/CustomApiResult: isSuccess(): errorCode = 0
2019-12-03 15:30:03.016 21871-25669/com.SpaceElves.box D/CustomApiResult: isSuccess(): return = true
2019-12-03 15:30:03.017 21871-21871/com.SpaceElves.box E/XHttp: --> Subscriber is onError
2019-12-03 15:30:03.017 21871-21871/com.SpaceElves.box E/XHttp: --> e instanceof ApiException, message:空指针错误
```

## 设备信息
- 设备名: 小米6
- Android版本: Android 9
- 设备型号 MI 6
- 系统版本 MIUI 11 9.11.28

**Comment by xuexiangjys** [comment]
代码可不是你这样写的。我的建议是，不要整得那么复杂，我看你的响应格式：
```
{"code":"00000000",
"msg":"服务调用成功！",
"data":{"token":"eaa824d3b50a53d38200084373e5f626"}}
```
你为什么要把code整成这样不伦不类的样子呢？直接改成int型就可以直接使用默认的API格式岂不是更好？而且自定义API也不是你这样写的，参考例子前要多结合自身实际情况去做。

**Comment by Weiyi-C** [comment]
code这个我也很无语，之前那个后端非要搞成这个样子，现在那个后端和iOS都离职了，我只有将就现在这个格式做，单独把后台改了iOS那边会崩

**Comment by xuexiangjys** [comment]
![image](https://user-images.githubusercontent.com/15059629/70103099-11923280-1675-11ea-96f5-6cfb028c9202.png)
理论上你用默认API直接就可以调用了，不需要自定义API

**Comment by Weiyi-C** [comment]
换默认的看了下，确实可以调用，但还是只有code=0，msg和data还是null，不知道哪里的问题
![image](https://user-images.githubusercontent.com/34223095/70108156-8b311d00-1683-11ea-9711-a931a4d07b57.png)

**Comment by xuexiangjys** [comment]
你的XHttp2版本低了，现在是1.0.3了

**Comment by Weiyi-C** [comment]
更新后出现新错误
![image](https://user-images.githubusercontent.com/34223095/70111088-19a99c80-168c-11ea-8559-4aedfe0ea90d.png)

```
2019-12-04 11:40:42.421 8825-8877/com.SpaceElves.box W/System.err: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 44 path $.data
2019-12-04 11:40:42.422 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
2019-12-04 11:40:42.422 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:932)
2019-12-04 11:40:42.423 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:897)
2019-12-04 11:40:42.423 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:846)
2019-12-04 11:40:42.424 8825-8877/com.SpaceElves.box W/System.err:     at com.xuexiang.xhttp2.transform.func.ApiResultFunc.parseCustomApiResult(ApiResultFunc.java:93)
2019-12-04 11:40:42.425 8825-8877/com.SpaceElves.box W/System.err:     at com.xuexiang.xhttp2.transform.func.ApiResultFunc.apply(ApiResultFunc.java:73)
2019-12-04 11:40:42.425 8825-8877/com.SpaceElves.box W/System.err:     at com.xuexiang.xhttp2.transform.func.ApiResultFunc.apply(ApiResultFunc.java:51)
2019-12-04 11:40:42.425 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
2019-12-04 11:40:42.426 8825-8877/com.SpaceElves.box W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
2019-12-04 11:40:42.427 8825-8877/com.SpaceElves.box W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
2019-12-04 11:40:42.427 8825-8877/com.SpaceElves.box W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
2019-12-04 11:40:42.428 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-12-04 11:40:42.428 8825-8877/com.SpaceElves.box W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
2019-12-04 11:40:42.429 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-12-04 11:40:42.430 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
2019-12-04 11:40:42.430 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-12-04 11:40:42.431 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
2019-12-04 11:40:42.431 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-12-04 11:40:42.431 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
2019-12-04 11:40:42.432 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-12-04 11:40:42.433 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2019-12-04 11:40:42.433 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
2019-12-04 11:40:42.434 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-12-04 11:40:42.434 8825-8877/com.SpaceElves.box W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-12-04 11:40:42.435 8825-8877/com.SpaceElves.box W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-12-04 11:40:42.435 8825-8877/com.SpaceElves.box W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-12-04 11:40:42.436 8825-8877/com.SpaceElves.box W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-12-04 11:40:42.436 8825-8877/com.SpaceElves.box W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-12-04 11:40:42.437 8825-8877/com.SpaceElves.box W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-12-04 11:40:42.439 8825-8877/com.SpaceElves.box W/System.err: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 44 path $.data
2019-12-04 11:40:42.439 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
2019-12-04 11:40:42.440 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
2019-12-04 11:40:42.440 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
2019-12-04 11:40:42.441 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
2019-12-04 11:40:42.441 8825-8877/com.SpaceElves.box W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
2019-12-04 11:40:42.442 8825-8877/com.SpaceElves.box W/System.err: 	... 28 more
```

**Comment by xuexiangjys** [comment]
你代码调用的有问题，泛型类型传入得有问题

**Comment by Weiyi-C** [comment]
泛型类解决了，但是获取到的data没有数据，也没看到报错
![调用方法](https://user-images.githubusercontent.com/34223095/70121497-aa42a580-16a9-11ea-80c0-106aaba16090.png)
![image](https://user-images.githubusercontent.com/34223095/70121472-97c86c00-16a9-11ea-8520-ac515252137c.png)

```
2019-12-04 15:25:42.928 12104-12157/com.SpaceElves.box I/XHttp: -------------------------------response-------------------------------
2019-12-04 15:25:42.929 12104-12157/com.SpaceElves.box I/XHttp: <-- 200 OK https://prod.api.spaceevels.com/test/res (476ms）
2019-12-04 15:25:42.929 12104-12157/com.SpaceElves.box I/XHttp:  
2019-12-04 15:25:42.929 12104-12157/com.SpaceElves.box I/XHttp: 	Server: nginx
2019-12-04 15:25:42.929 12104-12157/com.SpaceElves.box I/XHttp: 	Date: Wed, 04 Dec 2019 07:25:44 GMT
2019-12-04 15:25:42.929 12104-12157/com.SpaceElves.box I/XHttp: 	Content-Type: application/json; charset=UTF-8
2019-12-04 15:25:42.929 12104-12157/com.SpaceElves.box I/XHttp: 	Transfer-Encoding: chunked
2019-12-04 15:25:42.930 12104-12157/com.SpaceElves.box I/XHttp: 	Connection: keep-alive
2019-12-04 15:25:42.930 12104-12157/com.SpaceElves.box I/XHttp: 	X-Powered-By: PHP/7.3.0
2019-12-04 15:25:42.930 12104-12157/com.SpaceElves.box I/XHttp: 	Cache-Control: no-cache
2019-12-04 15:25:42.930 12104-12157/com.SpaceElves.box I/XHttp:  
2019-12-04 15:25:42.931 12104-12157/com.SpaceElves.box I/XHttp: 	body:{"code":"00000000","msg":"服务调用成功！","data":{"token":"63587108cf7bb617152a697d238cb4f5"}}
2019-12-04 15:25:42.931 12104-12157/com.SpaceElves.box I/XHttp: <-- END HTTP
2019-12-04 15:25:42.944 12104-12104/com.SpaceElves.box D/XHttp: --> Subscriber is Complete
```

**Comment by xuexiangjys** [comment]
原谅我已经没有耐心了，能不能多看看文档再写？
你传JSONObject几个意思？在你没能领悟XHttp2的精髓之前，我建议你还是不要用了。
原因参加：https://github.com/xuexiangjys/XHttp2/issues/8#issuecomment-543013924

**Comment by Weiyi-C** [comment]
我也没想用JSONObject啊，我就只想把收到的data原样拿到，然后我该干嘛干嘛就完了。  
用String，报
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 44 path $.data
```
用其它的好像也不太对，您给个建议该用个啥

目前我只有用keepJson能拿到数据，但keepJson好像不太符合您的设计，跳过了很多东西

**Comment by xuexiangjys** [comment]
你的水平我不想评价，但就你的json而言，你的泛型不是String，而是object，这个object有个成员参数是`token`。
```
{"code":"00000000",
"msg":"服务调用成功！",
"data":{"token":"eaa824d3b50a53d38200084373e5f626"}}
```

你的类型应该是.
```
public class TokenInfo {
    private String token;

}
```

这么简单的东西还整半天，真的是
